# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  grpc-report-generator-service:
    build:
      context: "C:\\Users\\ntdpy\\RiderProjects\\PaymentConvertionService"
      dockerfile: "Endpoints/GrpcServices/ReportService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/ReportService.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "reportservice:dev"
    ports: []
    volumes:
    - "C:\\Users\\ntdpy\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\ntdpy\\RiderProjects\\PaymentConvertionService\\Endpoints\\GrpcServices\\\
      ReportService:/app:rw"
    - "C:\\Users\\ntdpy\\RiderProjects\\PaymentConvertionService:/src:rw"
    working_dir: "/app"
  grpc-report-query-service:
    build:
      context: "C:\\Users\\ntdpy\\RiderProjects\\PaymentConvertionService"
      dockerfile: "Endpoints/GrpcServices/ReportQueryService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/ReportQueryService.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "reportqueryservice:dev"
    ports: []
    volumes:
    - "C:\\Users\\ntdpy\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\ntdpy\\RiderProjects\\PaymentConvertionService\\Endpoints\\GrpcServices\\\
      ReportQueryService:/app:rw"
    - "C:\\Users\\ntdpy\\RiderProjects\\PaymentConvertionService:/src:rw"
    working_dir: "/app"
  kafka-work-service:
    build:
      context: "C:\\Users\\ntdpy\\RiderProjects\\PaymentConvertionService"
      dockerfile: "Infrastructure/KafkaWorkerService/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/KafkaWorkerService.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "kafkaworkerservice:dev"
    ports: []
    volumes:
    - "C:\\Users\\ntdpy\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\ntdpy\\RiderProjects\\PaymentConvertionService\\Infrastructure\\\
      KafkaWorkerService:/app:rw"
    - "C:\\Users\\ntdpy\\RiderProjects\\PaymentConvertionService:/src:rw"
    working_dir: "/app"
